### ISSUE TITLE
Session cookie Name issue

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-session#11]
Be sure is used the session cookie name from session.global.php 

for instance ADMIN_SESSID 

instead of default one PHPSESSID

**Comment by arhimede** [comment]
related to https://github.com/dotkernel/frontend/issues/200

**Comment by alexmerlin** [comment]
Fixed in https://github.com/dotkernel/admin/pull/145 and https://github.com/dotkernel/frontend/pull/338
